version: '3.9'
services:
  # mongodb:
  #   image: mongo:5.0.8
  #   container_name: mongodb      
  #   environment:
  #       MONGO_INITDB_ROOT_USERNAME: admin
  #       MONGO_INITDB_ROOT_PASSWORD: admin
  #   restart: always
  api:
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      #- FLASK_ENV=development  #Entender melhor
      - MONGODB_DB=users
      - MONGODB_HOST=192.168.56.200
      - MONGODB_USER=restapi
      - MONGODB_PASSWORD=WG2THc8NW8qdT
    restart: always
    # depends_on:
    #   - mongodb
    volumes:
      - ./application:/app/application 
