apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-credentials
  namespace: default
spec:
  encryptedData:
    MONGODB_DB: {{ .Values.mongodb.database }}
    MONGODB_HOST: {{ .Values.mongodb.host }}
    MONGODB_PASSWORD: {{ .Values.mongodb.password }}
    MONGODB_USERNAME: 
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-credentials
      namespace: default
